### ISSUE TITLE
Enhancement: Support for ISD Compression

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ale#604]
When working with a large number of ISDs, the total data volume can start to become an issue. To combat this, some sort of compression for ISDs would be terrific. Right now, this is living in user land where one can compression/uncompress. This is to request a potential enhancement in ALE to standardize on one compression method. The idea being that down stream ISD consumers could choose to support compressed ISDs because they know what the compression is.

This [review of JSON](https://www.lucidchart.com/techblog/2019/12/06/json-compression-alternative-binary-formats-and-compression-methods/) suggests that simple [brotli compression](https://github.com/google/brotli) is both fast and efficient. It also seems that brotli is well supported.

**Comment by thareUSGS** [comment]
I like that brotli was designed for http streaming and there is a C++ header-only option (https://github.com/NewYaroslav/brotli-hpp). Perhaps the "usgs_csm_test" helper app could include a built-in compress/decompress method so that it can be made human-readable. Well, that app would need to support decompression since there is a method to inject a camera state into a GXP "sup" supplemental file.
